import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { trpcClient } from 'trpcClient'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  useEffect(() => {
    trpcClient.hello.query({name: 'Jorge'})
      .then((res) => console.log(res))
      .catch((err) => console.log(err))
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p >Hola parrafo 1</p>
      </main>
    </>
  )
}
